package com.xiangshan.user.entities;
// Generated 2018-3-15 20:45:24 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4479585177109011635L;
	private String userName;
	private String userPassword;
	private Integer userOld;
	private String userRole;
	private Date registerDate;

	public UserInfo() {
	}
	
	
	public UserInfo(String userName, String userPassword) {
		super();
		this.userName = userName;
		this.userPassword = userPassword;
	}


	public UserInfo(String userName, String userPassword, String userRole, Date registerDate) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userRole = userRole;
		this.registerDate = registerDate;
	}

	public UserInfo(String userName, String userPassword, Integer userOld, String userRole, Date registerDate) {
		this.userName = userName;
		this.userPassword = userPassword;
		this.userOld = userOld;
		this.userRole = userRole;
		this.registerDate = registerDate;
	}
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((userName == null) ? 0 : userName.hashCode());
		result = prime * result + ((userPassword == null) ? 0 : userPassword.hashCode());
		return result;
	}


	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		UserInfo other = (UserInfo) obj;
		if (userName == null) {
			if (other.userName != null)
				return false;
		} else if (!userName.equals(other.userName))
			return false;
		if (userPassword == null) {
			if (other.userPassword != null)
				return false;
		} else if (!userPassword.equals(other.userPassword))
			return false;
		return true;
	}


	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public Integer getUserOld() {
		return this.userOld;
	}

	public void setUserOld(Integer userOld) {
		this.userOld = userOld;
	}

	public String getUserRole() {
		return this.userRole;
	}

	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}

	public Date getRegisterDate() {
		return this.registerDate;
	}

	public void setRegisterDate(Date registerDate) {
		this.registerDate = registerDate;
	}


	@Override
	public String toString() {
		return "UserInfo [userName=" + userName + ", userPassword=" + userPassword + ", userOld=" + userOld
				+ ", userRole=" + userRole + ", registerDate=" + registerDate + "]";
	}
	
	
}
