package com.xiangshan.history.entities;
// Generated 2018-4-1 18:50:07 by Hibernate Tools 5.2.8.Final

import java.util.Date;

/**
 * QueryHistory generated by hbm2java
 */
public class QueryHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6621798444572019120L;
	private String id;
	private String subject;
	private String predicate;
	private String object;
	private String scope;
	private String timeSpaceScope;
	private String type;
	private Date createDate;
	private String userName;

	
	public QueryHistory() {
		super();
	}


	public QueryHistory(String id, String subject, String predicate, String object, String scope, String timeSpaceScope,
			String type, Date createDate, String userName) {
		this.id = id;
		this.subject = subject;
		this.predicate = predicate;
		this.object = object;
		this.scope = scope;
		this.timeSpaceScope = timeSpaceScope;
		this.type = type;
		this.createDate = createDate;
		this.userName = userName;
	}
	

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((object == null) ? 0 : object.hashCode());
		result = prime * result + ((predicate == null) ? 0 : predicate.hashCode());
		result = prime * result + ((scope == null) ? 0 : scope.hashCode());
		result = prime * result + ((subject == null) ? 0 : subject.hashCode());
		result = prime * result + ((timeSpaceScope == null) ? 0 : timeSpaceScope.hashCode());
		result = prime * result + ((type == null) ? 0 : type.hashCode());
		result = prime * result + ((userName == null) ? 0 : userName.hashCode());
		return result;
	}



	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		QueryHistory other = (QueryHistory) obj;
		if (object == null) {
			if (other.object != null)
				return false;
		} else if (!object.equals(other.object))
			return false;
		if (predicate == null) {
			if (other.predicate != null)
				return false;
		} else if (!predicate.equals(other.predicate))
			return false;
		if (scope == null) {
			if (other.scope != null)
				return false;
		} else if (!scope.equals(other.scope))
			return false;
		if (subject == null) {
			if (other.subject != null)
				return false;
		} else if (!subject.equals(other.subject))
			return false;
		if (timeSpaceScope == null) {
			if (other.timeSpaceScope != null)
				return false;
		} else if (!timeSpaceScope.equals(other.timeSpaceScope))
			return false;
		if (type == null) {
			if (other.type != null)
				return false;
		} else if (!type.equals(other.type))
			return false;
		if (userName == null) {
			if (other.userName != null)
				return false;
		} else if (!userName.equals(other.userName))
			return false;
		return true;
	}



	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	public String getPredicate() {
		return this.predicate;
	}

	public void setPredicate(String predicate) {
		this.predicate = predicate;
	}

	public String getObject() {
		return this.object;
	}

	public void setObject(String object) {
		this.object = object;
	}

	public String getScope() {
		return this.scope;
	}

	public void setScope(String scope) {
		this.scope = scope;
	}

	public String getTimeSpaceScope() {
		return this.timeSpaceScope;
	}

	public void setTimeSpaceScope(String timeSpaceScope) {
		this.timeSpaceScope = timeSpaceScope;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

}
